### ISSUE TITLE
disable_html_sanitization not working

### ISSUE THREAD

**Issue by capogreco** [denoland/deno_blog#119] opened 2023-03-09 11:08 UTC
markdown file looks like this:

```markdown
---
title: Hello world!
publish_date: 2023-03-09
disable_html_sanitization: true
---

This is my first blog post!

<iframe src="https://editor.p5js.org/capogreco/full/lqJs887v-"></iframe>
```

Which should show an embed of one of my p5 sketches.  Alas, it looks like this:

<img width="430" alt="Screenshot 2023-03-09 at 10 06 49 pm" src="https://user-images.githubusercontent.com/20375676/224005801-cc07a64a-e762-4133-9d3b-d7962047e9ab.png">

ie. the iframe was sanitized out.  Am I doing something wrong, or is disable_html_sanitization not working?

**Comment by hashrock** [comment] 2023-03-09 12:42
hmm, I'm not familiar with html sanitization, but it could be a problem on the deno_gfm side.

```ts
import { render } from "https://deno.land/x/gfm/mod.ts";

const html = `<div><wiggly worms="ewww">hello</wiggly>world</div>`
const body = render(html, {
  disableHtmlSanitization: true,
});

console.log(body)
// -> <div>helloworld</div>
```

**Comment by lino-levan** [comment] 2023-03-11 23:03
This is because `/x/blog` has not released a tag since last September. I will create a PR with the necessary changes to create a new tag. Hopefully #118 gets merged alongside it since that seems like a nice feature.

**Comment by lino-levan** [comment] 2023-03-11 23:04
To get around the tag issue now, you could always change your import map to:

```json
{
  "imports": {
    "blog": "https://raw.githubusercontent.com/denoland/deno_blog/main/blog.tsx"
  }
}
```

**Comment by lino-levan** [comment] 2023-03-11 23:05
By the way, @hashrock I can't reproduce your example

```ts
import { render } from "https://deno.land/x/gfm@0.2.1/mod.ts";

const html = `<div><wiggly worms="ewww">hello</wiggly>world</div>`
const body = render(html, {
  disableHtmlSanitization: true,
});

console.log(body) // <div><wiggly worms="ewww">hello</wiggly>world</div>
```

**Comment by lino-levan** [comment] 2023-03-11 23:10
ref #120

**Comment by capogreco** [comment] 2023-03-12 12:42
> To get around the tag issue now, you could always change your import map to:
> 
> ```json
> {
>   "imports": {
>     "blog": "https://raw.githubusercontent.com/denoland/deno_blog/main/blog.tsx"
>   }
> }
> ```

incredible - many thanks @lino-levan !!

**Comment by hashrock** [comment] 2023-03-12 14:12
@lino-levan 

Oh, you are right. I couldn't reproduce it anymore. I guess my cache was old.

**Comment by lino-levan** [comment] 2023-12-10 00:29
Should this issue be closed?

**Closed** 2023-12-19 18:46 UTC
