### ISSUE TITLE
Ordered & Unordered lists - numbers / dot points not visible

### ISSUE THREAD

**Issue by capogreco** [denoland/deno_blog#123] opened 2023-03-23 23:46 UTC
As it says in the title.  Neither lists with numbers, ie.

```
1. first item
2. second item
3. third item
```

... nor lists with dashes, ie.

```
- this item
- that item
- the other item
```

... are showing up with their respective numbers / dot points.  Indentation is correct, and the items are fine, just the numbers / dot points seem to be invisible.

Is this a global issue, or just me? Might be a CSS thing?

**Comment by roj1512** [comment] 2023-03-24 10:39
Duplicate of #23

**Closed** 2023-07-06 19:57 UTC
